branches:
  only:
   - master
   - release
language: python
python:
- '3.5'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
  fi
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
#- python3 tools/sqf_linter.py
deploy:
  provider: script
  script:
  - TAG=$(python3 tools/deploy.py 2>&1) 
    if [ $TAG != 0 ] && [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      git tag $TAG;
    fi