branches:
  only:
   - master
   - release
language: python
python:
- '3.5'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
  fi
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
#- python3 tools/sqf_linter.py
deploy:
  provider: releases
  upload: releases/*
  before_script: sed -i "s/#define VERSION.*/#define VERSION ${TAG}/" cScripts/script_component.hpp
  script: python3 tools/build.py -b release -d
  script: python3 tools/build.py -b release -p -d
  api_key:
    secure: ${GH_TOKEN}
  skip_cleanup: true
  draft: true
  on:
    tags: true