// Crewman
class B_crew_F : rhsusf_army_ocp_crewman {};
class B_T_Crew_F : rhsusf_army_ocp_crewman {};
class rhsusf_army_ocp_combatcrewman : rhsusf_army_ocp_crewman {};
class rhsusf_army_ucp_crewman : rhsusf_army_ocp_crewman {};
class rhsusf_army_ucp_combatcrewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_marpat_d_crewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_marpat_d_combatcrewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_lar_marpat_d_crewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_lar_marpat_d_combatcrewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_marpat_wd_crewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_marpat_wd_combatcrewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_lar_marpat_wd_crewman : rhsusf_army_ocp_crewman {};
class rhsusf_usmc_lar_marpat_wd_combatcrewman : rhsusf_army_ocp_crewman {};
class C_C : rhsusf_army_ocp_crewman {}; class C_C_1 : rhsusf_army_ocp_crewman {}; class C_C_2 : rhsusf_army_ocp_crewman {}; class C_C_3 : rhsusf_army_ocp_crewman {}; class C_C_4 : rhsusf_army_ocp_crewman {}; class C_C_5 : rhsusf_army_ocp_crewman {}; class C_C_6 : rhsusf_army_ocp_crewman {}; class C_C_7 : rhsusf_army_ocp_crewman {}; class C_C_8 : rhsusf_army_ocp_crewman {}; class C_C_9 : rhsusf_army_ocp_crewman {}; class C_C_10 : rhsusf_army_ocp_crewman {}; class C_C_11 : rhsusf_army_ocp_crewman {}; class C_C_12 : rhsusf_army_ocp_crewman {}; class C_C_13 : rhsusf_army_ocp_crewman {}; class C_C_14 : rhsusf_army_ocp_crewman {}; class C_C_15 : rhsusf_army_ocp_crewman {}; class C_C_16 : rhsusf_army_ocp_crewman {}; class C_C_17 : rhsusf_army_ocp_crewman {}; class C_C_18 : rhsusf_army_ocp_crewman {}; class C_C_19 : rhsusf_army_ocp_crewman {}; class C_C_20 : rhsusf_army_ocp_crewman {}; class C_C_21 : rhsusf_army_ocp_crewman {}; class C_C_22 : rhsusf_army_ocp_crewman {}; class C_C_23 : rhsusf_army_ocp_crewman {}; class C_C_24 : rhsusf_army_ocp_crewman {}; class C_C_25 : rhsusf_army_ocp_crewman {}; class C_C_26 : rhsusf_army_ocp_crewman {}; class C_C_27 : rhsusf_army_ocp_crewman {}; class C_C_28 : rhsusf_army_ocp_crewman {}; class C_C_29 : rhsusf_army_ocp_crewman {}; class C_C_30 : rhsusf_army_ocp_crewman {}; class C_C_31 : rhsusf_army_ocp_crewman {}; class C_C_32 : rhsusf_army_ocp_crewman {}; class C_C_33 : rhsusf_army_ocp_crewman {}; class C_C_34 : rhsusf_army_ocp_crewman {}; class C_C_35 : rhsusf_army_ocp_crewman {}; class C_C_36 : rhsusf_army_ocp_crewman {}; class C_C_37 : rhsusf_army_ocp_crewman {}; class C_C_38 : rhsusf_army_ocp_crewman {}; class C_C_39 : rhsusf_army_ocp_crewman {}; class C_C_40 : rhsusf_army_ocp_crewman {}; class C_C_41 : rhsusf_army_ocp_crewman {}; class C_C_42 : rhsusf_army_ocp_crewman {}; class C_C_43 : rhsusf_army_ocp_crewman {}; class C_C_44 : rhsusf_army_ocp_crewman {}; class C_C_45 : rhsusf_army_ocp_crewman {}; class C_C_46 : rhsusf_army_ocp_crewman {}; class C_C_47 : rhsusf_army_ocp_crewman {}; class C_C_48 : rhsusf_army_ocp_crewman {}; class C_C_49 : rhsusf_army_ocp_crewman {}; class C_C_50 : rhsusf_army_ocp_crewman {};
class CAV_Crewman : rhsusf_army_ocp_crewman {}; class CAV_Crewman_1 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_2 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_3 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_4 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_5 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_6 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_7 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_8 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_9 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_10 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_11 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_12 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_13 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_14 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_15 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_16 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_17 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_18 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_19 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_20 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_21 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_22 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_23 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_24 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_25 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_26 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_27 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_28 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_29 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_30 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_31 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_32 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_33 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_34 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_35 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_36 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_37 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_38 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_39 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_40 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_41 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_42 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_43 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_44 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_45 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_46 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_47 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_48 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_49 : rhsusf_army_ocp_crewman {}; class CAV_Crewman_50 : rhsusf_army_ocp_crewman {};

