// Officer
class B_officer_F : rhsusf_army_ocp_officer {};
class B_T_Officer_F : rhsusf_army_ocp_officer {};
class rhsusf_army_ucp_officer : rhsusf_army_ocp_officer {};
class C_OFF : rhsusf_army_ocp_officer {}; class C_OFF_1 : rhsusf_army_ocp_officer {}; class C_OFF_2 : rhsusf_army_ocp_officer {}; class C_OFF_3 : rhsusf_army_ocp_officer {}; class C_OFF_4 : rhsusf_army_ocp_officer {}; class C_OFF_5 : rhsusf_army_ocp_officer {}; class C_OFF_6 : rhsusf_army_ocp_officer {}; class C_OFF_7 : rhsusf_army_ocp_officer {}; class C_OFF_8 : rhsusf_army_ocp_officer {}; class C_OFF_9 : rhsusf_army_ocp_officer {}; class C_OFF_10 : rhsusf_army_ocp_officer {}; class C_OFF_11 : rhsusf_army_ocp_officer {}; class C_OFF_12 : rhsusf_army_ocp_officer {}; class C_OFF_13 : rhsusf_army_ocp_officer {}; class C_OFF_14 : rhsusf_army_ocp_officer {}; class C_OFF_15 : rhsusf_army_ocp_officer {}; class C_OFF_16 : rhsusf_army_ocp_officer {}; class C_OFF_17 : rhsusf_army_ocp_officer {}; class C_OFF_18 : rhsusf_army_ocp_officer {}; class C_OFF_19 : rhsusf_army_ocp_officer {}; class C_OFF_20 : rhsusf_army_ocp_officer {}; class C_OFF_21 : rhsusf_army_ocp_officer {}; class C_OFF_22 : rhsusf_army_ocp_officer {}; class C_OFF_23 : rhsusf_army_ocp_officer {}; class C_OFF_24 : rhsusf_army_ocp_officer {}; class C_OFF_25 : rhsusf_army_ocp_officer {}; class C_OFF_26 : rhsusf_army_ocp_officer {}; class C_OFF_27 : rhsusf_army_ocp_officer {}; class C_OFF_28 : rhsusf_army_ocp_officer {}; class C_OFF_29 : rhsusf_army_ocp_officer {}; class C_OFF_30 : rhsusf_army_ocp_officer {}; class C_OFF_31 : rhsusf_army_ocp_officer {}; class C_OFF_32 : rhsusf_army_ocp_officer {}; class C_OFF_33 : rhsusf_army_ocp_officer {}; class C_OFF_34 : rhsusf_army_ocp_officer {}; class C_OFF_35 : rhsusf_army_ocp_officer {}; class C_OFF_36 : rhsusf_army_ocp_officer {}; class C_OFF_37 : rhsusf_army_ocp_officer {}; class C_OFF_38 : rhsusf_army_ocp_officer {}; class C_OFF_39 : rhsusf_army_ocp_officer {}; class C_OFF_40 : rhsusf_army_ocp_officer {}; class C_OFF_41 : rhsusf_army_ocp_officer {}; class C_OFF_42 : rhsusf_army_ocp_officer {}; class C_OFF_43 : rhsusf_army_ocp_officer {}; class C_OFF_44 : rhsusf_army_ocp_officer {}; class C_OFF_45 : rhsusf_army_ocp_officer {}; class C_OFF_46 : rhsusf_army_ocp_officer {}; class C_OFF_47 : rhsusf_army_ocp_officer {}; class C_OFF_48 : rhsusf_army_ocp_officer {}; class C_OFF_49 : rhsusf_army_ocp_officer {}; class C_OFF_50 : rhsusf_army_ocp_officer {};


// JTAC
class C_JTAC_1 : C_JTAC {}; class C_JTAC_2 : C_JTAC {}; class C_JTAC_3 : C_JTAC {}; class C_JTAC_4 : C_JTAC {}; class C_JTAC_5 : C_JTAC {}; class C_JTAC_6 : C_JTAC {}; class C_JTAC_7 : C_JTAC {}; class C_JTAC_8 : C_JTAC {}; class C_JTAC_9 : C_JTAC {}; class C_JTAC_10 : C_JTAC {}; class C_JTAC_11 : C_JTAC {}; class C_JTAC_12 : C_JTAC {}; class C_JTAC_13 : C_JTAC {}; class C_JTAC_14 : C_JTAC {}; class C_JTAC_15 : C_JTAC {}; class C_JTAC_16 : C_JTAC {}; class C_JTAC_17 : C_JTAC {}; class C_JTAC_18 : C_JTAC {}; class C_JTAC_19 : C_JTAC {}; class C_JTAC_20 : C_JTAC {}; class C_JTAC_21 : C_JTAC {}; class C_JTAC_22 : C_JTAC {}; class C_JTAC_23 : C_JTAC {}; class C_JTAC_24 : C_JTAC {}; class C_JTAC_25 : C_JTAC {}; class C_JTAC_26 : C_JTAC {}; class C_JTAC_27 : C_JTAC {}; class C_JTAC_28 : C_JTAC {}; class C_JTAC_29 : C_JTAC {}; class C_JTAC_30 : C_JTAC {}; class C_JTAC_31 : C_JTAC {}; class C_JTAC_32 : C_JTAC {}; class C_JTAC_33 : C_JTAC {}; class C_JTAC_34 : C_JTAC {}; class C_JTAC_35 : C_JTAC {}; class C_JTAC_36 : C_JTAC {}; class C_JTAC_37 : C_JTAC {}; class C_JTAC_38 : C_JTAC {}; class C_JTAC_39 : C_JTAC {}; class C_JTAC_40 : C_JTAC {}; class C_JTAC_41 : C_JTAC {}; class C_JTAC_42 : C_JTAC {}; class C_JTAC_43 : C_JTAC {}; class C_JTAC_44 : C_JTAC {}; class C_JTAC_45 : C_JTAC {}; class C_JTAC_46 : C_JTAC {}; class C_JTAC_47 : C_JTAC {}; class C_JTAC_48 : C_JTAC {}; class C_JTAC_49 : C_JTAC {}; class C_JTAC_50 : C_JTAC {};


// Forward Observer
class C_FO_1 : C_FO {}; class C_FO_2 : C_FO {}; class C_FO_3 : C_FO {}; class C_FO_4 : C_FO {}; class C_FO_5 : C_FO {}; class C_FO_6 : C_FO {}; class C_FO_7 : C_FO {}; class C_FO_8 : C_FO {}; class C_FO_9 : C_FO {}; class C_FO_10 : C_FO {}; class C_FO_11 : C_FO {}; class C_FO_12 : C_FO {}; class C_FO_13 : C_FO {}; class C_FO_14 : C_FO {}; class C_FO_15 : C_FO {}; class C_FO_16 : C_FO {}; class C_FO_17 : C_FO {}; class C_FO_18 : C_FO {}; class C_FO_19 : C_FO {}; class C_FO_20 : C_FO {}; class C_FO_21 : C_FO {}; class C_FO_22 : C_FO {}; class C_FO_23 : C_FO {}; class C_FO_24 : C_FO {}; class C_FO_25 : C_FO {}; class C_FO_26 : C_FO {}; class C_FO_27 : C_FO {}; class C_FO_28 : C_FO {}; class C_FO_29 : C_FO {}; class C_FO_30 : C_FO {}; class C_FO_31 : C_FO {}; class C_FO_32 : C_FO {}; class C_FO_33 : C_FO {}; class C_FO_34 : C_FO {}; class C_FO_35 : C_FO {}; class C_FO_36 : C_FO {}; class C_FO_37 : C_FO {}; class C_FO_38 : C_FO {}; class C_FO_39 : C_FO {}; class C_FO_40 : C_FO {}; class C_FO_41 : C_FO {}; class C_FO_42 : C_FO {}; class C_FO_43 : C_FO {}; class C_FO_44 : C_FO {}; class C_FO_45 : C_FO {}; class C_FO_46 : C_FO {}; class C_FO_47 : C_FO {}; class C_FO_48 : C_FO {}; class C_FO_49 : C_FO {}; class C_FO_50 : C_FO {};
