// Helicopter Pilot
class B_Helipilot_F : rhsusf_army_ocp_helipilot {};
class B_T_Helipilot_F : rhsusf_army_ocp_helipilot {};
class rhsusf_army_ucp_helipilot : rhsusf_army_ocp_helipilot {};
class rhsusf_usmc_marpat_d_helipilot : rhsusf_army_ocp_helipilot {};
class rhsusf_usmc_marpat_wd_helipilot : rhsusf_army_ocp_helipilot {};
class CAV_HeliPilot : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_1 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_2 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_3 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_4 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_5 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_6 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_7 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_8 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_9 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_10 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_11 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_12 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_13 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_14 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_15 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_16 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_17 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_18 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_19 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_20 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_21 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_22 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_23 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_24 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_25 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_26 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_27 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_28 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_29 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_30 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_31 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_32 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_33 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_34 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_35 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_36 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_37 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_38 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_39 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_40 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_41 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_42 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_43 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_44 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_45 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_46 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_47 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_48 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_49 : rhsusf_army_ocp_helipilot {}; class CAV_HeliPilot_50 : rhsusf_army_ocp_helipilot {};

// Helicopter Crew
class B_helicrew_F : rhsusf_army_ocp_helicrew {};
class B_T_Helicrew_F : rhsusf_army_ocp_helicrew {};
class rhsusf_army_ucp_helicrew : rhsusf_army_ocp_helicrew {};
class rhsusf_usmc_marpat_d_helicrew : rhsusf_army_ocp_helicrew {};
class rhsusf_usmc_marpat_wd_helicrew : rhsusf_army_ocp_helicrew {};
class CAV_HeliCrew : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_1 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_2 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_3 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_4 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_5 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_6 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_7 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_8 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_9 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_10 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_11 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_12 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_13 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_14 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_15 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_16 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_17 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_18 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_19 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_20 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_21 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_22 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_23 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_24 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_25 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_26 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_27 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_28 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_29 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_30 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_31 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_32 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_33 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_34 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_35 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_36 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_37 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_38 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_39 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_40 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_41 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_42 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_43 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_44 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_45 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_46 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_47 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_48 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_49 : rhsusf_army_ocp_helicrew {}; class CAV_HeliCrew_50 : rhsusf_army_ocp_helicrew {};
