#include "..\script_component.hpp";
/* 
 * Author: CPL.Brostrom.A
 * This function initzialises all the default mission loadouts.
 *
 * Arguments:
 * None
 *
 * Example:
 * call cScripts_fnc_initAceLoadouts
 *
 * Public: No
 */

#ifdef DEBUG_MODE
    if !(is3DEN) then {
        ["Setting up CAV Default ACE Arsenal loadouts."] call FUNC(logInfo);
    } else {
        diag_log format["[%1] %2: %3", QUOTE(PREFIX), "INFO", "Setting up CAV Default ACE Arsenal loadouts in eden."];
    };
#endif

private _empty = [[],[],[],[],[],[],"","",[],["","","","","",""]];
["<empty>", _empty] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - Squad Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_HuntIR_monitor",1],["ACE_EarPlugs",1],["ACE_quikclot",10],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_squadleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["SmokeShellBlue",4,1],["SmokeShellRed",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_HandFlare_Red",2,1]]],["B_AssaultPack_khk",[["ACE_EarPlugs",1],["ACE_quikclot",6],["ACE_tourniquet",4],["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_headset_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Fire Team Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhsusf_200rnd_556x45_mixed_box",1,200],["rhs_mag_m67",2,1],["SmokeShell",4,1],["ACE_Chemlight_HiRed",1,1]]],["B_AssaultPack_khk",[["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["SmokeShellGreen",1,1],["SmokeShellBlue",2,1],["SmokeShellRed",1,1],["ACE_Chemlight_HiRed",1,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Fire Team Leader (M320)", [["rhs_weap_m4a1_m320","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],["rhs_mag_M433_HEDP",1],""],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_MapTools",1],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_grenadier",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhsusf_200rnd_556x45_mixed_box",1,200],["rhs_mag_M433_HEDP",2,1],["ACE_HuntIR_M203",2,1],["rhs_mag_m714_White",3,1],["ACE_Chemlight_HiRed",1,1]]],["B_AssaultPack_khk",[["ACE_personalAidKit",1],["ACRE_PRC343",1],["rhs_mag_m714_White",1,1],["rhs_mag_m713_Red",4,1],["rhs_mag_m662_red",2,1],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["SmokeShellBlue",2,1],["SmokeShellRed",1,1],["ACE_Chemlight_HiRed",1,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Automatic Rifleman", [["rhs_weap_m249_pip_S_para","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ELCAN_ard",["rhsusf_200rnd_556x45_mixed_box",200],[],""],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_MapTools",1],["ACRE_PRC343",1]]],["rhsusf_spcs_ocp_saw",[["rhsusf_200rnd_556x45_mixed_box",3,200],["rhs_mag_30Rnd_556x45_M855A1_PMAG",2,30],["SmokeShell",2,1]]],["B_AssaultPack_khk",[["ACE_personalAidKit",1],["rhsusf_200rnd_556x45_mixed_box",1,200],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],["rhs_mag_m67",2,1],["SmokeShell",2,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Grenadier", [["rhs_weap_m4a1_m320","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["rhs_mag_M433_HEDP",1],""],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_personalAidKit",1]]],["rhsusf_spcs_ocp_grenadier",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1],["rhs_mag_M433_HEDP",2,1]]],["B_AssaultPack_khk",[["ACE_MapTools",1],["ACRE_PRC343",1],["rhs_mag_M433_HEDP",10,1],["rhs_mag_m714_White",6,1],["rhs_mag_m662_red",2,1],["ACE_HuntIR_M203",2,1]]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Rifleman", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",11,30],["rhs_mag_M433_HEDP",6,1],["rhs_mag_m714_White",1,1]]],["B_AssaultPack_khk",[["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["rhs_mag_m714_White",3,1],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Rifleman (LAT)", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],["tf47_at4_heat","","","",[],[],""],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",11,30],["rhs_mag_M433_HEDP",6,1],["rhs_mag_m714_White",1,1]]],["B_AssaultPack_khk",[["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["rhs_mag_m714_White",3,1],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Designated Marksman", [["rhs_weap_sr25_ec","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_su230a",["rhsusf_20Rnd_762x51_SR25_m993_Mag",20],[],"rhsusf_acc_harris_bipod"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",2]]],["rhsusf_spcs_ocp_sniper",[["rhsusf_20Rnd_762x51_SR25_m993_Mag",5,20],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["B_AssaultPack_khk",[["ACE_tourniquet",2],["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["B_IR_Grenade",1,1]]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Combat Life Saver", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",11,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["ACE_Chemlight_HiRed",1,1]]],["B_AssaultPack_khk",[["ACE_MapTools",1],["ACE_personalAidKit",4],["ACE_EarPlugs",1],["ACE_quikclot",14],["ACE_tourniquet",6],["ACE_morphine",6],["ACE_epinephrine",6],["ACRE_PRC343",1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",1,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Company Staff", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_EntrenchingTool",1],["ACE_SpraypaintGreen",1],["ACE_EarPlugs",1],["ACE_quikclot",2],["ACRE_PRC152",1],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_squadleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",6,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellRed",3,1],["SmokeShellGreen",3,1],["SmokeShellBlue",3,1],["SmokeShellYellow",3,1],["ACE_Chemlight_HiRed",1,1]]],["B_AssaultPack_khk",[["ACE_EarPlugs",1],["ACE_quikclot",14],["ACE_tourniquet",4],["ACE_MapTools",1],["ACRE_PRC343",1],["SmokeShellPurple",3,1],["ACE_Chemlight_HiRed",1,1],["Chemlight_blue",2,1],["B_IR_Grenade",3,1]]],"rhsusf_ach_helmet_headset_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Platoon Sergeant", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_SpraypaintGreen",1],["ACE_EarPlugs",1],["ACE_quikclot",1],["ACRE_PRC152",1],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_squadleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellRed",3,1],["SmokeShellGreen",3,1],["SmokeShellBlue",3,1],["SmokeShellYellow",1,1]]],["B_AssaultPack_khk",[["ACE_EarPlugs",1],["ACE_quikclot",15],["ACE_tourniquet",4],["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["SmokeShellYellow",2,1],["SmokeShellPurple",3,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",3,1]]],"rhsusf_ach_helmet_headset_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Platoon Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_SpraypaintGreen",1],["ACE_EarPlugs",1],["ACE_quikclot",1],["ACRE_PRC152",1],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_squadleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellRed",3,1],["SmokeShellGreen",3,1],["SmokeShellBlue",3,1],["SmokeShellYellow",1,1]]],["B_AssaultPack_khk",[["ACE_EarPlugs",1],["ACE_quikclot",15],["ACE_tourniquet",4],["ACE_personalAidKit",1],["ACE_MapTools",1],["ACRE_PRC343",1],["SmokeShellYellow",2,1],["SmokeShellPurple",3,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",3,1]]],"rhsusf_ach_helmet_headset_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Platoon Medic", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",12],["ACRE_PRC152",1],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_medic",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",2,1],["SmokeShellBlue",2,1],["SmokeShellPurple",2,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["B_Kitbag_cbr",[["ACE_surgicalKit",1],["ACE_salineIV",10],["ACE_morphine",15],["ACE_elasticBandage",40],["ACE_EarPlugs",1],["ACE_quikclot",40],["ACE_personalAidKit",6],["ACE_epinephrine",2],["B_IR_Grenade",1,1]]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - Machinegunner Team Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_teamleader",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",6,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",2,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["B_Kitbag_cbr",[["ACE_MapTools",1],["ACE_SpareBarrel",1,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Machinegunner", [["rhs_weap_m240B","rhsusf_acc_ARDEC_M240","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_MDO",["rhsusf_100Rnd_762x51_m62_tracer",100],[],""],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_MapTools",1]]],["rhsusf_spcs_ocp_machinegunner",[["ACRE_PRC343",1],["rhs_mag_m67",1,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["rhsusf_100Rnd_762x51_m62_tracer",3,100]]],["B_AssaultPack_khk",[["rhsusf_100Rnd_762x51_m62_tracer",2,100]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - MAAWS Gunner (HE)", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],["tf47_m3maaws","","","tf47_optic_m3maaws",["tf47_m3maaws_HE",1],[],""],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",3]]],["rhsusf_spcs_ocp_rifleman",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["B_AssaultPack_khk",[["ACE_tourniquet",1],["ACE_MapTools",1]]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - MAAWS Assistant (HE)", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["ACE_MapTools",1],["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["B_Kitbag_cbr",[["B_IR_Grenade",1,1],["tf47_m3maaws_HE",4,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - MAAWS Gunner (AT)", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],["tf47_m3maaws","","","tf47_optic_m3maaws",["tf47_m3maaws_HEAT",1],[],""],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",3]]],["rhsusf_spcs_ocp_rifleman",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["B_AssaultPack_khk",[["ACE_tourniquet",1],["ACE_MapTools",1]]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - MAAWS Assistant (AT)", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["B_Kitbag_cbr",[["ACE_MapTools",1],["B_IR_Grenade",1,1],["Cav_m3maaws_HEAT_CS",2,1],["tf47_m3maaws_HEAT",1,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - AA Gunner", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],["rhs_weap_fim92","","","",["rhs_fim92_mag",1],[],""],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["B_AssaultPack_khk",[["ACE_MapTools",1],["B_IR_Grenade",1,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - AA Assistant", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["B_Kitbag_cbr",[["ACE_MapTools",1],["rhs_fim92_mag",2,1]]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - MK.14 Team Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1],["SmokeShellRed",1,1],["SmokeShellBlue",2,1]]],["RHS_Mk19_Tripod_Bag",[]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - MK.14 Gunner", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_MapTools",1]]],["rhsusf_spcs_ocp_rifleman",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["RHS_Mk19_Gun_Bag",[]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - MK.14 Tripod", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4]]],["rhsusf_spcs_ocp_rifleman",[["ACE_MapTools",1],["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["RHS_Mk19_Tripod_Bag",[]],"rhsusf_ach_helmet_camo_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

["[7CAV] Charlie - Mortar Automatic Rifleman", [["rhs_weap_m249_pip_S_para","rhsusf_acc_SFMB556","","rhsusf_acc_ELCAN",["rhsusf_200rnd_556x45_mixed_box",200],[],""],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_MapTools",1],["ACRE_PRC343",1]]],["rhsusf_spcs_ocp_saw",[["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1],["rhsusf_200rnd_556x45_mixed_box",2,200]]],["B_Mortar_01_support_F",[]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Mortar Team Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_RangeTable_82mm",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",3],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_teamleader_alt",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["SmokeShellRed",1,1],["SmokeShellBlue",2,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["B_Mortar_01_support_F",[]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Mortar Gunner", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_DAGR",1],["ACE_RangeTable_82mm",1],["ACE_EarPlugs",1],["ACE_quikclot",16],["ACE_tourniquet",4],["ACE_MapTools",1]]],["rhsusf_spcs_ocp_rifleman_alt",[["ACRE_PRC343",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1]]],["B_Mortar_01_weapon_F",[]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",[],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["[7CAV] Charlie - Mortar Squad Leader", [["rhs_weap_m4a1_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_tdstubby_blk"],[],[],["LOP_U_ISTS_Fatigue_19",[["ACE_microDAGR",1],["ACE_IR_Strobe_Item",1],["ACE_RangeTable_82mm",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_quikclot",10],["ACRE_PRC152",1],["ACRE_PRC152",1]]],["rhsusf_spcs_ocp_squadleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1],["SmokeShellRed",1,1],["SmokeShellBlue",2,1]]],["B_Mortar_01_weapon_F",[]],"rhsusf_ach_helmet_ocp","G_Shades_Blue",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","ItemRadioAcreFlagged","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;

#ifdef DEBUG_MODE
    if !(is3DEN) then {
            ["CAV Default ACE Arsenal loadouts completed."] call FUNC(logInfo);
    } else {
        diag_log format["[%1] %2: %3", QUOTE(PREFIX), "INFO", "CAV Default ACE Arsenal loadouts added in eden."];
    };
#endif
