name: Create Artifacts
on: workflow_dispatch
jobs:
  build:
    name: Create And Upload Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build releases
        run: ./tools/deploy.sh DevBuild_${{ github.ref_name }}-$(git rev-parse --short HEAD)

      - name: Upload releases
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_DevBuild_${{ github.ref_name }}-$(git rev-parse --short HEAD)
          path: release/*

      - name: Upload release debug only
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_Debug-DevBuild_${{ github.ref_name }}-$(git rev-parse --short HEAD)
          path: release/cScripts_Debug-DevBuild_${{ github.ref_name }}-$(git rev-parse --short HEAD).zip
