name: Deploy Tag Artifacts
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Create And Upload Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build releases
        run: ./tools/deploy.sh ${{github.ref_name}}

      - name: Upload releases
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_Releases
          path: release/*
