name: Deploy
on:
  push:
      branches:
        - main
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get the commit
        id: get_commit_number
        run: echo "{name}={COMMIT}" >> $(git rev-parse --short HEAD)

      - name: Build releases
        run: ./tools/deploy.sh DevBuild-${{ steps.get_commit_number.outputs.COMMIT }}

      - name: Upload release (cScripts)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts-${{ steps.get_commit_number.outputs.COMMIT }}.zip
          path: release/cScripts-${{ steps.get_commit_number.outputs.COMMIT }}.zip

      - name: Upload release (Compositions)
        uses: actions/upload-artifact@v3
        with:
          name: Compositions-${{ steps.get_commit_number.outputs.COMMIT }}.zip
          path: release/Compositions-${{ steps.get_commit_number.outputs.COMMIT }}.zip

      - name: Upload release (cScripts_Debug)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_Debug-${{ steps.get_commit_number.outputs.COMMIT }}.zip
          path: release/cScripts_Debug-${{ steps.get_commit_number.outputs.COMMIT }}.zip

      - name: Upload release (cScripts_NoRadio)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_NoRadio-${{ steps.get_commit_number.outputs.COMMIT }}.zip
          path: release/cScripts_NoRadio-${{ steps.get_commit_number.outputs.COMMIT }}.zip

      - name: Upload release (cScripts_NoLoadouts)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_NoLoadouts-${{ steps.get_commit_number.outputs.COMMIT }}.zip
          path: release/cScripts_NoLoadouts-${{ steps.get_commit_number.outputs.COMMIT }}.zip
