name: Deploy
on:
  release:
      types: [published]
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install zip
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build release
        run: ./tools/deploy.sh ${{ steps.get_version.outputs.VERSION }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: yey
          draft: false
          prerelease: false

      - name: Upload Release cScripts
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: release/cScripts-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: cScripts-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release cScripts (PUBLIC)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: release/cScripts_PUBLIC-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: cScripts_PUBLIC-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release (Compositions)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/Compositions-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: Compositions-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip