name: Deploy Devbuild Artifacts
on:
  push:
      branches:
        - main
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build releases
        run: ./tools/deploy.sh DevBuild-$(git rev-parse --short HEAD)

      - name: Upload release (cScripts)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts-DevBuild-$(git rev-parse --short HEAD).zip
          path: release/cScripts-DevBuild-$(git rev-parse --short HEAD).zip

      - name: Upload release (Compositions)
        uses: actions/upload-artifact@v3
        with:
          name: Compositions-DevBuild-$(git rev-parse --short HEAD).zip
          path: release/Compositions-DevBuild-$(git rev-parse --short HEAD).zip

      - name: Upload release (cScripts_Debug)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_Debug-DevBuild-$(git rev-parse --short HEAD).zip
          path: release/cScripts_Debug-DevBuild-$(git rev-parse --short HEAD).zip


      - name: Upload release (cScripts_NoRadio)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_NoRadio-DevBuild-$(git rev-parse --short HEAD).zip
          path: release/cScripts_NoRadio-DevBuild-$(git rev-parse --short HEAD).zip

      - name: Upload release (cScripts_NoLoadouts)
        uses: actions/upload-artifact@v3
        with:
          name: cScripts_NoLoadouts-DevBuild-$(git rev-parse --short HEAD).zip
          path: release/cScripts_NoLoadouts-DevBuild-$(git rev-parse --short HEAD).zip
