name: Deploy
on:
  release:
      types: [ published, prereleased ]
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build release
        run: ./tools/deploy.sh ${{ steps.get_version.outputs.VERSION }}

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false

      - name: Upload Release cScripts
        uses: JasonEtco/upload-to-release@master
        with:
          args: release/cScripts-${{ steps.get_version.outputs.VERSION }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release cScripts (PUBLIC)
        uses: JasonEtco/upload-to-release@master
        with:
          args: release/cScripts_PUBLIC-${{ steps.get_version.outputs.VERSION }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release cScripts (Compositions)
        uses: JasonEtco/upload-to-release@master
        with:
          args: release/Compositions-${{ steps.get_version.outputs.VERSION }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}