name: Deploy
on:
  release:
      types: [ published, prereleased ]
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build release
        run: ./tools/deploy.sh ${{ steps.get_version.outputs.VERSION }}

      - name: Upload releases
        uses: actions/upload-artifact@v2
        with:
           path: release/*.zip
