name: Deploy Release
on:
  release:
      types: [ published ]
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build releases
        run: ./tools/deploy.sh ${{github.ref_name}}

      - name: Upload release (cScripts)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: cScripts-${{github.ref_name}}.zip
          file: release/cScripts-${{github.ref_name}}.zip

      - name: Upload release (Compositions)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: Compositions-${{github.ref_name}}.zip
          file: release/Compositions-${{github.ref_name}}.zip

      - name: Upload release (cScripts_Debug)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: cScripts_Debug-${{github.ref_name}}.zip
          file: release/cScripts_Debug-${{github.ref_name}}.zip


      - name: Upload release (cScripts_NoRadio)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: cScripts_NoRadio-${{github.ref_name}}.zip
          file: release/cScripts_NoRadio-${{github.ref_name}}.zip

      - name: Upload release (cScripts_NoLoadouts)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: cScripts_NoLoadouts-${{github.ref_name}}.zip
          file: release/cScripts_NoLoadouts-${{github.ref_name}}.zip
